#
#	compilation parameters for SNAP Python
#

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CXXFLAGS += -fPIC -D__STDC_LIMIT_MACROS
  LDFLAGS += -shared
else ifeq ($(UNAME), Darwin)
  # OS X flags
  LDFLAGS += -lpython -dynamiclib
else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CXXFLAGS += -shared -D__STDC_LIMIT_MACROS
  LIBS += -lpython2.6
endif

