#
#	compilation parameters for SNAP Python
#

UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  SWIGFLAGS += -D_CMPWARN -D__stdcall -DSW_SNAPPY
  CXXFLAGS += -fPIC -D__STDC_LIMIT_MACROS -DSW_SNAPPY -fopenmp
  LDFLAGS += -shared -fopenmp
else ifeq ($(UNAME), Darwin)
  # OS X flags
  SWIGFLAGS += -D_CMPWARN -D__stdcall -DSW_SNAPPY
  CXXFLAGS += -DSW_SNAPPY
  LDFLAGS += -lpython -dynamiclib
else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  SWIGFLAGS += -D_CMPWARN -D__stdcall -DSW_SNAPPY
  CXXFLAGS += -shared -D__STDC_LIMIT_MACROS -DSW_SNAPPY
  LIBS += -lpython2.6
endif

