#
#	Makefile for running 
#

all:

# benchmark.py is obsolete and does not work with the latest Snap.py
#	see ../test for a working version
tneanet:
	python tneanet.py

# benchmark.py is obsolete and does not work with the latest Snap.py
benchmark:
	python benchmark.py

clean:
	rm -rf results *.graph
